server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zulkarshaikh/configStore
          username: zulkar.shaikh@gmail.com
          password: Allahmiya@786
          search-paths:
           - '*service'